controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: ackermann_steering_controller/AckermannSteeringController
      

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster


# joint_broad:
#   ros__parameters:

diff_cont:
  ros__parameters:
    publish_rate: 30.0
    reference_timeout: 0.5
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: true
    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_steer_joint, front_left_steer_joint]
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    wheelbase: 0.3429
    front_wheel_track: 0.25
    rear_wheel_track: 0.25
    front_wheels_radius: 0.056
    rear_wheels_radius: 0.056
    max_steering_speed: 1.5707963267948966
    max_steering_angle: 0.42

    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    # twist_covariance_diagonal: {0.0, 7.0, 14.0, 21.0, 28.0, 35.0}
    # pose_covariance_diagonal: {0.0, 7.0, 14.0, 21.0, 28.0, 35.0}

